"""Add user_id to JobRole model

Revision ID: 0c7e41284516
Revises: f150bcd8fc97
Create Date: 2024-08-24 20:12:55.490925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0c7e41284516'
down_revision = 'f150bcd8fc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobrole', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'jobrole', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobrole', type_='foreignkey')
    op.drop_column('jobrole', 'user_id')
    # ### end Alembic commands ###
