"""Remove author id from PostBase model

Revision ID: 103c57c6c8b6
Revises: d9779daa1f46
Create Date: 2024-08-22 21:37:58.526275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '103c57c6c8b6'
down_revision = 'd9779daa1f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
