"""Remove user from job roles

Revision ID: b592a2ae97f4
Revises: 0c7e41284516
Create Date: 2024-08-24 20:55:31.870347

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b592a2ae97f4'
down_revision = '0c7e41284516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobrole_user_id_fkey', 'jobrole', type_='foreignkey')
    op.drop_column('jobrole', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobrole', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('jobrole_user_id_fkey', 'jobrole', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
