"""Add column color to Item model

Revision ID: fa9e3376edcf
Revises: 2bcbf02e2000
Create Date: 2024-08-21 22:51:30.252563

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fa9e3376edcf'
down_revision = '2bcbf02e2000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'color')
    # ### end Alembic commands ###
